/*
Pegasus - Motor Controller Unit software for HL,HLP,Storm,Vortex and future projects.

Contributors: Pujit Gandhi,Pratik Rout,Olay,Saksham

This file acts as an entry point for major code flow responsible for motor control
and system monitoring for voltage,temperature,current and other physical parameters.

main()                          : Contains code blocks for sanity,fault & error 
                                  detection, can communication.
HAL_TIM_PeriodElapsedCallback() : Contain code blocks for motor control operation. (20kHz frequency)
HAL_TIM_IC_CaptureCallback()    : Contain code blocks for intial motion sensing.
HAL_GPIO_EXTI_Callback          : Contain code blocks for reseting position.

*/

/* Includes ------------------------------------------------------------------*/
#include "main.h"

/* Variable declaration ------------------------------------------------------*/
float Duty;
volatile uint32_t ICValue;
volatile uint32_t z_trig = 0;
uint8_t app_version = 0;
uint8_t pvd_trig_flag = 0;

char message[50] = {0};

/* externs -------------------------------------------------------------------*/
extern motorControl_t motorControl;
extern can_t can;
extern adc_t analog;
extern foc_t foc;
extern terminal_t terminal;

fnr_states fnr;
hard_fault_cause hard_fault_c;
Current_Off_Calc curr_off = {.W_Phase_Offset = 0, .V_Phase_Offset = 0};
FOC_Logging foc_log = {0};

/* Private function prototypes -----------------------------------------------*/
typedef struct __attribute__((packed))
{
	uint32_t flags;
  uint32_t magic;
} shared_memory_t;

image_hdr_t image_hdr __attribute__((section(".image_hdr"))) = {
    .image_magic       = IMAGE_MAGIC,
    .image_hdr_version = IMAGE_HEADER_VERSION,
    .crc               = IMAGE_CRC,
    .data_size         = 0,
    .image_type        = 0,
    .version_major     = 0,
    .version_minor     = 0,
    .version_patch     = 0,
#ifdef APP1
    .active_app = 1,
#endif
#ifdef APP2
    .active_app = 2,
#endif
    // .vector_addr = (uint32_t)&vector_table,
    // GIT_SHA is generated by Makefile
};

shared_memory_t sharedmemory __attribute__((section(".shared_memory")));

//main function. 
int main(void) 
{
  //system clock init.
  SYSTEM_INIT();

  // Update_BOR_Counter();

  // Boot_Counter();

  // read_hard_fault_cause();

  //function to keep drive disable intially.
  MotorControl_Init();

  //can init
  can.setup();

  //adc init and start via DMA
  if(analog.start_dma(&hadc1, (uint32_t*) analog.bufferData, ADC_NoOfConversion) != OK) 
  {
    Error_Handler();
  }

  HAL_Delay(2000);

  bootup_config();

  // Get_and_Send_UIID();

  Current_Sensor_offset_cal();

  //FOC_initialize();
  Open_loop6_initialize();

  //enabling motor control interrupts , ABZ+PWM sensing interrpts.
  ENABLE_PERIPHERALS();

  //while loop running on CLK frequency.
  while (1) 
  {
    PVD_Counter_Update();

    CAN_Transmit_routine();

    ANALOG_READING();
    
    FAULT_DETECTION();

    Throttle_Control_routine();

    Led_Toggle();
  }
}

/* USER CODE BEGIN 4 */
//callback to read pwm value from encoder
void HAL_TIM_IC_CaptureCallback(TIM_HandleTypeDef *htim)
{
	if (htim->Channel == HAL_TIM_ACTIVE_CHANNEL_1)  // If the interrupt is triggered by channel 1
	{
		// Read the IC value
		ICValue = HAL_TIM_ReadCapturedValue(htim, TIM_CHANNEL_1);

		if (ICValue != 0)
		{
			// calculate the Duty Cycle
			Duty = (HAL_TIM_ReadCapturedValue(htim, TIM_CHANNEL_2) * 100.0)/(float)ICValue;
		}
	}
}

//callback to read Z data from encoder
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
  if(GPIO_Pin == GPIO_PIN_7) // If The INT Source Is EXTI Line9_5 (PE7 Pin)
  {
    foc.rho = 0.0;
    foc.rho_prev = 0.0;
    z_trig += 1;
  }
}

void HAL_PWR_PVDCallback(void) 
{
  // Handle PVD event
  // For example, toggle an LED or log the event
  pvd_trig_flag = 1;
}

void hard_fault_handler_c(uint32_t *stack_address) 
{
  // Read the general purpose registers and the special registers
  uint32_t stacked_lr = stack_address[5];
  uint32_t stacked_pc = stack_address[6];

  // Log or process the extracted register values for debugging
  // For example, send them over a serial interface or store in non-volatile memory
  EEPROM_Write_Data_LR_Register(stacked_lr);
  EEPROM_Write_Data_PC_Register(stacked_pc);
  // Reset the controller
  NVIC_SystemReset();
}

void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)  {
  /* Prevent unused argument(s) compilation warning */
  
  if(htim->Instance == TIM7)
  {
    motorControl.drive.check = DRIVE_DISABLE;
    HAL_TIM_Base_Stop_IT(&htim17);
    switch (upgrade_state)
    {
    case UPGRADE_INIT:
      handle_upgrade_init();
      break;
    case UPGRADE_RECEIVE_DATA:
      handle_rceive_data();
      break;
    case UPGRADE_PAUSE:
      handle_upgrade_pause();
      HAL_TIM_Base_Stop_IT(&htim7);
      motorControl.drive.check = DRIVE_ENABLE;
      HAL_TIM_Base_Start_IT(&htim17);
      break;
    case UPGRADE_RESUME:
      handle_upgrade_resume();
      break;
    case UPGRADE_COMPLETE:
      handle_upgrade_complete();
      break;
    case UPGRADE_FAILED:
      HAL_TIM_Base_Stop_IT(&htim7);
      motorControl.drive.check = DRIVE_ENABLE;
      HAL_TIM_Base_Start_IT(&htim17);
      break;
    default:
      break;
    }
  }

  if(htim->Instance==TIM17) 
  {
    if (motorControl.drive.check == DRIVE_DISABLE){DRIVE_STOP();}

    //motor angle,current
    READ_MOTOR_PHASE_CURRENT();

    FOC_READ_MOTOR_POSITION();

    // FOC_step();
    
    Open_loop6_step();

    FOC_SPACE_VECTOR_MODULATION();

    //rt_OneStep();
  }
}

void rt_OneStep(){
  // static boolean_T OverrunFlag = false;

  // if(OverrunFlag) {
  //   rtmSetErrorStatus(rtM, "Overrun");
  //   return;
  // }
  // OverrunFlag = true;

  Open_loop6_step();

  FOC_SPACE_VECTOR_MODULATION();

  // OverrunFlag=false;

}

void switch_partition_and_reset()
{
	sharedmemory.flags |= BL_SWITCH_PARTITION;
	NVIC_SystemReset();
}

/**
  * @brief This function handles Hard fault interrupt.
  */
__attribute__((naked)) void HardFault_Handler(void) 
{
  __asm volatile (
      "TST lr, #4 \n"           // Test bit 2 of LR to determine the active stack pointer
      "ITE EQ \n"               // If-Then-Else instruction
      "MRSEQ r0, MSP \n"        // If equal (bit 2 is 0), move MSP to R0
      "MRSNE r0, PSP \n"        // If not equal (bit 2 is 1), move PSP to R0
      "B hard_fault_handler_c \n" // Branch to the C handler
  );
}

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
   
