/*
Pegasus - Motor Controller Unit software for HL,HLP,Storm,Vortex and future projects.

Contributors: Pujit Gandhi,Pratik Rout,Olay,Saksham

This file acts as an entry point for major code flow responsible for motor control
and system monitoring for voltage,temperature,current and other physical parameters.

main()                          : Contains code blocks for sanity,fault & error 
                                  detection, can communication.
HAL_TIM_PeriodElapsedCallback() : Contain code blocks for motor control operation. (20kHz frequency)
HAL_TIM_IC_CaptureCallback()    : Contain code blocks for intial motion sensing.
HAL_GPIO_EXTI_Callback          : Contain code blocks for reseting position.

*/



/* Includes ------------------------------------------------------------------*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include "main.h"
#include "math_func.h"
#include "adc.h"
#include "dma.h"
#include "fdcan.h"
#include "tim.h"
#include "usart.h"
#include "gpio.h"

#include "led_AL.h"
#include "adc_AL.h"
#include "fdcan_AL.h"
#include "temp_AL.h"

#include "v_f_control.h"
#include "vector_control.h"

#include "motor_param.h"
#include "eeprom_AL.h"
#include "flash.h"
#include "eepromCRC.h"
#include "vehicle.h"
#include "sanity.h"
#include "foc_blockset.h"
#include "microcontroller.h"

#include "config.h"
#include "can_tp_app.h"
#include "bootloaderFunctions.h"
#include "firmware_upgrade_app.h"
#include "isotp/isotp_types.h"


/* Variable declaration ------------------------------------------------------*/

#ifndef HSEM_ID_0
#define HSEM_ID_0 (0U) /* HW semaphore 0*/
#endif

/* externs -------------------------------------------------------------------*/
extern led_t          led;
extern can_t          can;
extern adc_t          analog;
extern terminal_t     terminal;
extern struct gpio    io;
extern motorControl_t motorControl;
extern vehicle_t vehicle;

/* Private function prototypes -----------------------------------------------*/

float Duty;
float freq_rpm = 0.0;
float throttle_percent = 0.0;
volatile uint32_t ICValue;
volatile uint32_t angle_curr = 0, angle_prev = 0;
uint32_t z_count=50;
volatile uint32_t z_trig = 0;
uint8_t reset_flag = 0;
uint8_t app_version = 0;
uint8_t cantp_config_flag = 0;
uint8_t interrupt_flag = 0;
uint8_t start_flag = 0;
uint8_t acc_flag = 0;
uint8_t deacc_flag = 0;

int count_duty=0;
int counter_100ms=0;
int counter_current_ms = 0;
int counter_encoder_ms = 0;
uint8_t counter_abnormal_run = 0;
 
int pwm_pulse=0;
int z_pulse=0;    

char message[50] = {0};

typedef struct __attribute__((packed))
{
	uint32_t flags;
  uint32_t magic;
} shared_memory_t;

image_hdr_t image_hdr __attribute__((section(".image_hdr"))) = {
    .image_magic       = IMAGE_MAGIC,
    .image_hdr_version = IMAGE_HEADER_VERSION,
    .crc               = IMAGE_CRC,
    .data_size         = 0,
    .image_type        = 0,
    .version_major     = 0,
    .version_minor     = 0,
    .version_patch     = 0,
#ifdef APP1
    .active_app = 1,
#endif
#ifdef APP2
    .active_app = 2,
#endif
    // .vector_addr = (uint32_t)&vector_table,
    // GIT_SHA is generated by Makefile
};

shared_memory_t sharedmemory __attribute__((section(".shared_memory")));

//main function. 
int main(void) {

  //system clock init.
  SYSTEM_INIT();

  //can init
  can.setup();

  //adc init and start via DMA
  if(analog.start_dma(&hadc1, (uint32_t*) analog.bufferData, ADC_NoOfConversion) != OK) {
     Error_Handler();
  }

  HAL_Delay(5000);
  
  //function to keep drive disable intially.
  MotorControl_Init();
  // HAL_Delay(100); //commented
  
  //function to perform sanity checks at ignition.
  RUN_SANITY();
  // HAL_Delay(9000); //commented

  //enabling motor control interrupts , ABZ+PWM sensing interrpts.
  ENABLE_PERIPHERALS();
  // HAL_Delay(100);  //commented

  //read previous odometer data.
  EEPROM_Read_Data();

  bootup_config();

  start_flag = 1;
  
  //while loop running on CLK frequency.
  while (1) 
  {
      //function to continously monitor mcu faults and errors.
      ANALOG_READING();
      FAULT_READING();
      //read fnr ,throttle
      READ_FNR();
      READ_THROTTLE();
      HAL_Delay(1);
  }
}

uint8_t get_conifg_flag(){
  return cantp_config_flag;
}

uint8_t get_interrupt_flag(){
  return interrupt_flag;
}

void set_config_flag(uint8_t value){
  cantp_config_flag = value;

}

void set_interrupt_flag(uint8_t value){
  interrupt_flag = value;
}

/* USER CODE BEGIN 4 */
//callback to read pwm value from encoder
void HAL_TIM_IC_CaptureCallback(TIM_HandleTypeDef *htim)
{
	if (htim->Channel == HAL_TIM_ACTIVE_CHANNEL_1)  // If the interrupt is triggered by channel 1
	{

    count_duty++;

    if(count_duty>=50){count_duty=1;}

		// Read the IC value
		ICValue = HAL_TIM_ReadCapturedValue(htim, TIM_CHANNEL_1);

		if (ICValue != 0)
		{
			// calculate the Duty Cycle
			Duty = (HAL_TIM_ReadCapturedValue(htim, TIM_CHANNEL_2) * 100.0)/(float)ICValue;
		}
	}
}
//callback to read Z data from encoder
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
    if(GPIO_Pin == GPIO_PIN_7) // If The INT Source Is EXTI Line9_5 (PE7 Pin)
    {
      reset_flag = 1;
      z_trig += 1;
    }
}

void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)  {
  /* Prevent unused argument(s) compilation warning */
  if(htim->Instance == TIM4)
  {
    CAN_Communication(vehicle.odometer,vehicle.trip,vehicle.speed);
  }

  if(htim->Instance == TIM15)
  {
    CAN_Logging();
  }

  if(htim->Instance == TIM16)
  {
    Calculate_OTS(terminal.w.sen);
  }

  if(htim->Instance == TIM8)
  {
    if(vehicle.odo_change_status == ODO_UPDATE)
    {
      EEPROM_Write_Data(vehicle.odometer);
      vehicle.odo_change_status = NO_ODO_UPDATE;
    }
  }

  if(htim->Instance == TIM7)
  {
    motorControl.drive.check = DRIVE_DISABLE;
    HAL_TIM_Base_Stop_IT(&htim17);
    switch (upgrade_state)
    {
    case UPGRADE_INIT:
      handle_upgrade_init();
      break;
    case UPGRADE_RECEIVE_DATA:
      handle_rceive_data();
      break;
    case UPGRADE_PAUSE:
      handle_upgrade_pause();
      HAL_TIM_Base_Stop_IT(&htim7);
      motorControl.drive.check = DRIVE_ENABLE;
      HAL_TIM_Base_Start_IT(&htim17);
      break;
    case UPGRADE_RESUME:
      handle_upgrade_resume();
      break;
    case UPGRADE_COMPLETE:
      handle_upgrade_complete();
      break;
    case UPGRADE_FAILED:
      HAL_TIM_Base_Stop_IT(&htim7);
      motorControl.drive.check = DRIVE_ENABLE;
      HAL_TIM_Base_Start_IT(&htim17);
      break;
    default:
      break;
    }
  }
  
  if(htim->Instance==TIM17) {

        
        //turn led red/green depending on drive status
        if(motorControl.drive.check == DRIVE_DISABLE) {
          //rgb gpio
          HAL_GPIO_WritePin(GPIOD, GPIO_PIN_10, GPIO_PIN_SET);
          HAL_GPIO_WritePin(GPIOD, GPIO_PIN_11, GPIO_PIN_SET);
          HAL_GPIO_WritePin(GPIOD, GPIO_PIN_12, GPIO_PIN_RESET);
        }
        else if(motorControl.drive.check == DRIVE_ENABLE) {
          //  rgb gpio
          HAL_GPIO_WritePin(GPIOD, GPIO_PIN_10, GPIO_PIN_RESET);
          HAL_GPIO_WritePin(GPIOD, GPIO_PIN_11, GPIO_PIN_SET);
          HAL_GPIO_WritePin(GPIOD, GPIO_PIN_12, GPIO_PIN_RESET);

          HAL_GPIO_WritePin(GPIOD, GPIO_PIN_15, GPIO_PIN_SET);

        }

          //motor angle,current
          READ_MOTOR_POSITION();
          READ_MOTOR_PHASE_CURRENT();

          //sanity checks to be perfomed at 20kHz
          SAFETY_AND_ERRORS();

          //main function for motor control operation.
          VECTOR_FOC_Control();
          motorControl.encoder.previous = motorControl.encoder.value;
          angle_prev = angle_curr;

          counter_100ms++;
          counter_current_ms++;
          counter_encoder_ms++;
          counter_abnormal_run++;
  }
}


void switch_partition_and_reset()
{
	sharedmemory.flags |= BL_SWITCH_PARTITION;
	NVIC_SystemReset();
}


/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
   
